### ISSUE TITLE
No constructor found with matching signature.

### ISSUE THREAD

**Issue by vladislavbagnyuk** [MarkusJx/node-java-bridge#29]
```
appendClasspath(CTILL_SCALE_JAR_PATH);

const guard = stdout.enableRedirect(
  (_, data) => {
    console.log('Stdout:', data);
  },
  (_, data) => {
    console.error('Stderr:', data);
  }
);

const System = importClass('java.lang.System');
System.out.println('|Hello world');
const JLong = importClass('java.lang.Long');
const JString = importClass('java.lang.String');
const JCTillScale = importClass('cz.prins.scale.CTillScale');
const liveSleep = new JLong(12000);
System.out.println(liveSleep.getClassSync());
this.scale = new JCTillScale(liveSleep);
```
    
<img width="668" alt="Screenshot 2022-11-08 at 15 56 05" src="https://user-images.githubusercontent.com/23129955/200597767-229dc61e-3d0d-48d0-a8c4-b686bccbaaf4.png">

Hello,

I have a code that calls my Java library (cz.prins.scale.CTillScale), that has a constructor that has signature cz.prins.scale.CTillScale(java.lang.Long), but when I pass a java.lang.Long argument it throws **Unhandled Exception Error: No constructor found with matching signature.** . I attached code example and console log with errors. I'm using openjdk 11.0.16.1, node.js 16 and the latest version of your library. Could you please help me?

Thank you

**Comment by MarkusJx** [comment]
This may be related to node.js truncating some arguments for some reason, I'll look into it, but as I don't have a lot of time right now, this may take a while so just be patient :)

**Comment by MarkusJx** [comment]
Didn't quite find the issue you described, but found something which should be close enough...
[This test case](https://github.com/MarkusJx/node-java-bridge/blob/fix/brokenConstructors/test/ClassTest.test.ts#L35) should represent your code somewhat

Anyways, will create a new beta release for you to test the fix in the next days, I'll inform you once this is the case

**Comment by vladislavbagnyuk** [comment]
Thank you!

**Comment by MarkusJx** [comment]
Should be fixed in the latest beta release `v2.1.6-beta.1`.
Please provide feedback if this is working, so I can create a proper release

**Comment by vladislavbagnyuk** [comment]
Unfortunately I still get the same error on `v2.1.6-beta.1` release as before. I have tried different Node versions (16, 18 and 19), but it still doesn't work.

**Comment by MarkusJx** [comment]
Ok, so the thing actually not working is passing java objects for (somewhat) primitives to any method. Ill fix this in the following days, in the meanwhile, you can just pass primitive javascript types, those will be converted automatically to java types, no need to specify the java class required:
```ts
appendClasspath(CTILL_SCALE_JAR_PATH);

const guard = stdout.enableRedirect(
  (_, data) => {
    console.log('Stdout:', data);
  },
  (_, data) => {
    console.error('Stderr:', data);
  }
);

const System = importClass('java.lang.System');
System.out.println('|Hello world');
const JCTillScale = importClass('cz.prins.scale.CTillScale');

// 'BigInt' is converted to any long type.
// 'number' can be converted to int, float, double and long though
const liveSleep = 12000n;
this.scale = new JCTillScale(liveSleep);
```

**Comment by MarkusJx** [comment]
The newest beta release `v2.1.6-beta.2` *should* fix your problem

**Comment by vladislavbagnyuk** [comment]
Thank you! Seems like it's finally working.
